[project]
name = "scrapy"
version = "0.1.0"
description = "Trial for Web Scraping"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "lxml>=5.4.0",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
]
